// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	domain "github.com/Te8va/wallet/internal/domain"
)

// MockwalletServ is a mock of walletServ interface.
type MockwalletServ struct {
	ctrl     *gomock.Controller
	recorder *MockwalletServMockRecorder
}

// MockwalletServMockRecorder is the mock recorder for MockwalletServ.
type MockwalletServMockRecorder struct {
	mock *MockwalletServ
}

// NewMockwalletServ creates a new mock instance.
func NewMockwalletServ(ctrl *gomock.Controller) *MockwalletServ {
	mock := &MockwalletServ{ctrl: ctrl}
	mock.recorder = &MockwalletServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletServ) EXPECT() *MockwalletServMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockwalletServ) GetBalance(ctx context.Context, walletID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, walletID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockwalletServMockRecorder) GetBalance(ctx, walletID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockwalletServ)(nil).GetBalance), ctx, walletID)
}

// ProcessTransaction mocks base method.
func (m *MockwalletServ) ProcessTransaction(ctx context.Context, walletID string, opType domain.OperationType, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTransaction", ctx, walletID, opType, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTransaction indicates an expected call of ProcessTransaction.
func (mr *MockwalletServMockRecorder) ProcessTransaction(ctx, walletID, opType, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTransaction", reflect.TypeOf((*MockwalletServ)(nil).ProcessTransaction), ctx, walletID, opType, amount)
}
